apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-svc
spec:
  selector:   # 연결할 대상의 라벨명
    app: my-nginx
  ports:
  - port: 8080        # 이 서비스의 포트번호
    targetPort: 80    # 컨테이너의 서비스 포트번호
  type: NodePort      # NodePort는 외부에서 접근 가능한 네트워크 드라이버(Private Subnet)
---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-svc
spec:
  selector:
    app: my-nginx1
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
  type: ClusterIP      # type의 기본값으로 생략하면 이것으로 지정됨