apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ca-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret                  # 쿠버네티스 외부(AWS 등)의 비밀 정보를 클러스터 내부로 연동하겠다는 선언
metadata:
  name: mysql-aws-secret              # 이 ExternalSecret 오브젝트 자체의 이름입니다.
  namespace: default                  # 이 리소스가 생성될 네임스페이스입니다. 기본값인 default
spec:
  refreshInterval: "1h"               # AWS Secrets Manager의 최신 값을 1시간마다 주기적으로 동기화합니다
  secretStoreRef:
    name: aws-secretsmanager          # 미리 만들어둔 연결 설정(ClusterSecretStore)의 이름입니다.
    kind: ClusterSecretStore          # 참조할 저장소 오브젝트의 종류가 클러스터 전용(ClusterSecretStore)임을 명시합니다
  target:
    name: mysql-secret-from-aws       # AWS에서 가져온 값으로 쿠버네티스 내부 시크릿을 새로 생성할 때 붙일 이름입니다.
    creationPolicy: Owner             # 이 ExternalSecret이 삭제될때 생성된 쿠버네티스 시크릿도 함께 자동 삭제되도록
  data:
  - secretKey: MYSQL_ROOT_PASSWORD    # 생성될 쿠버네티스 시크릿 내부에서 사용할 키 이름입니다. (파드가 이 이름으로)
    remoteRef:
      key: std09-mysql-secret         # 실제 AWS Secrets Manager에 저장되어 있는 시크릿의 이름 또는 경로 입니다.
      property: MYSQL_ROOT_PASSWORD   # AWS 시크릿 내부(JSON 형태)에서 가져올 특정 필드(KEY) 이름입니다.
