apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-document-file
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>Nginx with ConfigMap</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-configmap-pod
spec:
  containers:
    - name: nginx-configmap-container
      image: nginx:1.31.3-alpine
      ports:
      - containerPort: 80
      volumeMounts:
      - name: config-volume
        mountPath: /usr/share/nginx/html/index.html
        subPath: index.html
  volumes:
  - name: config-volume
    configMap:
      name: nginx-document-file