# kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret     # 이 이름은 POD의 env에서 사용할
  labels:
    app: db
data:
  ROOT_PASSWORD: "cXdlcmFzZGY=" # key명, 가져오는 것은 "", base64로 인코딩된 값

---   # 파일과 파일의 구분은 ---로 한다.
apiVersion: v1    # kubectl api-resources에 나오는 버전 값
kind: Pod
metadata:
  name: secret-mysql-pod  # 파드의 이름 정의
  labels: 
    app: secret-mysql
spec:
  containers:
    - name: secret-mysql-container
      image: mysql:8.0
      # command: ["/bin/sh","-c","env; sleep 120"]
      env:
        - name: MYSQL_ROOT_PASSWORD   # 환경변수명으로 mysql에서 반드시 필요한 값
          valueFrom:
            secretKeyRef:
              name: mysql-secret   # 참조할 ConfigMap 이름
              key: ROOT_PASSWORD        # 가져올 데이터의 키 이름
# EOF