apiVersion: v1
kind: Pod
metadata:
  name: pod-label-01
  labels:
    job: web
    type: infra
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine


apiVersion: v1
kind: Pod
metadata:
  name: pod-label-02
  labels:
    job: web
    type: infra
spec:
  containers:
  - name: container02
    image:  nginx:1.29.4-alpine    

apiVersion: v1
kind: Pod
metadata:
  name: pod-label-03
  labels:
    job: web
spec:
  containers:
  - name: container03
    image:  nginx:1.29.4-alpine    

apiVersion: v1
kind: Pod
metadata:
  name: pod-label-04
  labels:
    job: web
spec:
  containers:
  - name: container04
    image:  nginx:1.29.4-alpine    

apiVersion: v1
kind: Pod
metadata:
  name: pod-label-05
  labels:
    type: infra
spec:
  containers:
  - name: container05
    image:  nginx:1.29.4-alpine    

apiVersion: v1
kind: Pod
metadata:
  name: pod-label-06
  labels:
    type: infra
spec:
  containers:
  - name: container06
    image:  nginx:1.29.4-alpine    
