# ######################################################################
# kubectl 명령어 기본 사용법
# ######################################################################

# ######################################################################
# kubectl 명령어는 Kubernetes 클러스터와 상호작용하기 위한 기본 도구입니다.
# 이 문서는 kubectl 명령어의 기본 사용법과 주요 옵션에 대해 설명합니다.
# ======================================================================
# kubectl 명령어 기본 형식 : kubectl <command> [type] [name] [flags]
# <command> : 수행할 작업 (예: get, describe, create, delete 등)
# [type] : 리소스 유형 (예: pod, service, deployment 등)
# [name] : 리소스 이름 (특정 리소스를 지정할 때 사용)
# [flags] : 추가 옵션 및 플래그
# ======================================================================
# 주요 옵션 설명
# -o <output_format> : 출력 형식 지정 (예: json, yaml, wide 등)
# -n <namespace> : 특정 네임스페이스 지정
# --kubeconfig=<file_path> : 특정 kubeconfig 파일 사용
# --context=<context_name> : 특정 컨텍스트 사용
# --dry-run=client | server | none : 실제 실행되지 않고 시뮬레이션만 수행
# --force : 강제 삭제 등 특정 작업을 강제로 수행
# ######################################################################

# ######################################################################
# 주요 command 예시
# ######################################################################
# ======================================================================
# 리소스 조회 : kubectl get [type] [name] [flags]
# ----------------------------------------------------------------------
kubectl get pods
kubectl get services -n kube-system
# ======================================================================
# 리소스 상세 정보 조회 : kubectl describe [type] [name] [flags]
# ----------------------------------------------------------------------
kubectl describe pod my-pod
kubectl describe service my-service -n kube-system
# ======================================================================
# 리소스 생성 : kubectl create -f <file_path> [flags]
# ----------------------------------------------------------------------
kubectl create -f my-deployment.yaml
# ======================================================================
# 리소스 삭제 : kubectl delete [type] [name] [flags]
# ----------------------------------------------------------------------
kubectl delete pod my-pod
kubectl delete -f my-deployment.yaml
# ======================================================================
# kubectl exec : kubectl exec -it <pod_name> -- <command>
# ----------------------------------------------------------------------
kubectl exec -it my-pod -- /bin/bash
# ###################################################################### 

# ######################################################################
# 주요 Type 약어 정리
# ######################################################################
# Pod : po
# Service : svc
# Ingress : ing
# Endpoint : ep
# Deployment : deploy
# ReplicaSet : rs
# Namespace : ns
# ConfigMap : cm
# Secret : secret
# PersistentVolume : pv
# PersistentVolumeClaim : pvc
# ###################################################################### 

# ######################################################################
# 파드 나 서비스 등 장애 또는 오류로 인한 문제 발생시 확인 사항
# ######################################################################
#  1. 파드 상태 확인 (kubectl get pods)
#  2. 파드 로그 확인 (kubectl logs <pod_name>)
#  3. 파드 상세 정보 확인 (kubectl describe pod <pod_name>)
#  4. 서비스 상태 확인 (kubectl get svc)
#  5. 서비스 상세 정보 확인 (kubectl describe svc <service_name>)
#  6. 서비스가 파드들과 잘 연결되었는지 확인 (kubectl get endpoints <service_name>)
#  7. 네임스페이스 상태 확인 (kubectl get ns)
#  8. 클러스터 노드 상태 확인 (kubectl get nodes)
#  9. 클러스터 이벤트 확인 (kubectl get events)
# 10. apiVersion 및 리소스 유형 확인 (kubectl api-resources) 
#                           또는 (kubectl api-resources | grep <type>) 
#                           또는 (kubectl explain <type>) 
# ######################################################################