# ################################################################################
# ELB중 Application Load Balancer(ALB) 실습
# ################################################################################
# 1. 2개의 EC2 인스턴스를 생성하고, 각각 Nginx를 설치하고, index.html을 수정한다.(alb/ec2nginx80, alb/ec2nginx8080)
# 2-1. 인스턴스 생성과 함께 Nginx 설치와 index.html 수정이 자동으로 이루어지도록 user-data.sh를 작성한다.
# 2-2. 두 번째 인스턴스의 nginx는 8080 포트로 listen하도록 user-data.sh를 작성한다.
# 2-3. 인스턴스 생성에 필요한 작업 파일들을 GitHub에 업로드한다.
# --------------------------------------------------------------------------------
# 로컬 레포지토리 디렉토리 구조
./AWS
│  README.md
│
└─alb
    │  작업순서.ini
    │
    ├─ec2nginx80
    │      index.html
    │      user-data.sh
    │
    └─ec2nginx8080
            index.html
            user-data.sh
# --------------------------------------------------------------------------------
# 3. 80포트와 8080포트로 listen하는 두 개의 EC2 인스턴스를 대상으로 ALB를 생성한다.
# User Data: 아래 셀스크립트를 복사하여 붙여넣기 한다.
# 첫 번째 80포트 사용할 인스턴스
#!/bin/bash
curl -o /tmp/user-data.sh https://raw.githubusercontent.com/csjin21c/ex-aws/refs/heads/main/alb/ec2nginx80/user-data.sh
chmod +x /tmp/user-data.sh
/tmp/user-data.sh

# 두 번째 8080포트 사용할 인스턴스
#!/bin/bash
curl -o /tmp/user-data.sh https://raw.githubusercontent.com/csjin21c/ex-aws/refs/heads/main/alb/ec2nginx8080/user-data.sh
chmod +x /tmp/user-data.sh
/tmp/user-data.sh

# ================================================================================
# 4. Application Load Balancer(ALB) 생성
# 4-1. 2개의 Target Group 생성하고 각각 80포트와 8080포트의 인스턴스를 등록한다.
# 4-2. ALB 생성 시, 80포트로 listen하도록 설정하고, 80포트의 Target Group을 등록한다.
# 4-3. 두 개의 로드 밸런서를 생성하고 모두 80포트로 각각 두 개의 인스턴스의 Nginx를 확인한다.