apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    job: web
    type: infra
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    job: db
    type: infra
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    job: srv
    type: infra
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    job: web
    type: dev
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod5
  labels:
    job: db
    type: dev
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod6
  labels:
    job: srv
    type: dev
spec:
  containers:
  - name: container01
    image:  nginx:1.29.4-alpine