apiVersion: v1
kind: Pod
metadata: 
  name: web-monitor-pod
  labels:
    app: target-app
spec:
  containers:
    # 1. 웹서비스 컨테이너(nginx)
    - name: main-web
      image: nginx:1.31.3-alpine
      ports:
        - containerPort: 80
      volumeMounts:                   # 컨테이너끼리 통신 안해도 되게 하나의 볼륨을 같이 바라보게해 그곳의 데이터를 공유하게함. 정확히 이 설명이 맞는지는 잘 모르겠음. 이것의 이점도
        - name: log-storage           # 볼륨 선언부(섹션)에 정의된 볼륨 이름
          mountPath: /var/log/nginx   # nginx 로그 저장 경로, 컨테이너 내부 경로

    # 2. 사이드카 컨테이너: 웹서비스(nginx) 로그 모니터링
    - name: sidecar-monitor
      image: busybox:1.28
      command: ['sh','-c',"tail -f /var/log/nginx/access.log"]
      volumeMounts:
        - name: log-storage
          mountPath: /var/log/nginx   # 메인 컨테이너의 로그 저장소 공유
          readOnly: true              # 사이드카는 읽기만 허용

  volumes:
    - name: log-storage
      emptyDir: {}