apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP   # Kubernetes 서비스의 기본 드라이버(생략이 가능)
  selector:
    app: target-mysql-app # 연결할 파드의 라벨
  ports:
    - name: http
      protocol: TCP
      port: 80        # External 포트와 이어질 포트
      targetPort: 80  # 컨테이너 대기(통신) 포트

