# Pod with Init Container 예제

apiVersion: v1    # kubectl api-resources에 나오는 버전 값
kind: Pod
metadata:
  name: my-init-pod  # 파드의 이름 정의
  labels:
    app: my-init
    owner: bipa17

spec:
  containers:
    - name: my-nginx-container  # 컨테이너 이름 정의
      image: nginx:1.31.3-alpine  # 도커 이미지 이름(ECR에 있는 이미지)
      # image: 925047940866.dkr.ecr.ca-central-1.amazonaws.com/std09/nginx:v3
      ports:
        - containerPort: 80   # 설정 아님, 가시적 정보 제공 목적
  initContainers:   # containers에 정의된 주 컨테이너 시작전 초기화 목적의 컨테이너
    - name: wait-for-db
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup mysql-svc; do echo waiting for db; sleep 2; done"]

