apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-nginx
spec:
  containers:
  - name: my-nginx-container
    image: nginx:1.31.3-alpine
    volumeMounts:
    - name: my-hostpath-volume   # volume 세션에 정의된 볼륨 이름
      mountPath: /usr/share/nginx/html
    - name: my-hostpath-log-volume
      mountPath: /var/log/nginx
  volumes:
  - name: my-hostpath-volume
    hostPath:
      path: /var/www/html
      type: Directory
  - name: my-hostpath-log-volume
    hostPath:
      path: /var/log/nginx
      type: Directory
# =========================================================
# type: Directory, DirectoryOrCreate, FileOrCreate, File
# Directory: 정의한 경로의 디렉토리가 존재해야함.
# DirectoryOrCreate: kubelet이 필요에 따라 디렉토리를 생성하되 kubelet의 소유권과 권한(755)을 부여
# File: 정의한 경로의 파일이 존재해야함.
# FileOrCreate: kubelet이 필요에 따라 디렉토리를 생성하되 kubelet의 소유권과 권한(644)을 부여
