apiVersion: v1
kind: Service
metadata:
  name: svc-frontend-web
spec:
  selector:
    job: web
  ports:
    - port: 8081

apiVersion: v1
kind: Service
metadata:
  name: svc-infra
spec:
  selector:
    type: infra
  ports:
    - port: 8082

apiVersion: v1
kind: Service
metadata:
  name: svc-infra-web
spec:
  selector:
    job: web
    type: infra
  ports:
    - port: 8083