services:
  service-mysql:
    # apparmor 보안 프로필을 비활성화하여 컨테이너가 호스트 시스템의 NFS 볼륨에 접근할 수 있도록 설정
    # security_opt: ["apparmor:unconfined"]
    image: minseung12/insmysql:v1
    build:
      context: /home/ga05/from_instructor_docker-compose/workspace/build/mysql
      dockerfile: Dockerfile
      platforms: ["linux/amd64"]
    container_name: mysql-primary-container
    environment:
      # 1. 루트 비밀번호 (필수)
      MYSQL_ROOT_PASSWORD: "ian1234!"
      # 2. 초기 데이터베이스 생성 (선택)
      MYSQL_DATABASE: "iandb"
      # 3. 일반 사용자 계정 생성 (선택 - 보안상 권장)
      MYSQL_USER: "ian"
      MYSQL_PASSWORD: "ian1234!"
      # 4. 시간대 설정 (컨테이너 시스템 레벨)
      TZ: "Asia/Seoul"
      DB_HOST: 10.0.136.231
      DB_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - board-network:

networks:
  board-network:
    driver: bridge
